# import params from training config
src:
  ckpt: 'ckpt/librispeech_words_fixed_labels_sd0/best_att.pth'
  config: 'config/libri/lib_word_example.yaml'
data:
  corpus:                                 
    name: 'single_word'                   # Specify corpus
    path: '/om2/user/imgriff/projects/cocktail_party/datasets/GigaSpeech_top_200_words/' # Path to raw LibriSpeech dataset
    dev_split: ['GigaSpeech_top_200_words']  # Name of data splits to be used as validation set
    test_split: ['GigaSpeech_top_200_words'] # Hack to avoid debugging for now 02/25/2022 

  audio:                                  # Attributes of audio feature
    feat_type: 'fbank'
    feat_dim:  40
    frame_length: 25                      # ms
    frame_shift: 10                       # ms
    dither: 0                             # random dither audio, 0: no dither
    apply_cmvn: True
    delta_order: 0                        # 0: do nothing, 1: add delta, 2: add delta and accelerate
    delta_window_size: 0
    resample: True
    saved_rate: 44100
    new_rate: 16000
  text:
    mode: 'word'                       # 'character'/'word'/'subword'
    vocab_file: 'tests/sample_data/librispeech_words-10k.vocab'

decode:
  beam_size: 10
  min_len_ratio: 0.01
  max_len_ratio: 0.07
#   lm_path: 'ckpt/lm_example_sd0/best_ppx.pth'
#   lm_config: 'config/libri/lm_example.yaml'
  lm_weight: 0
