
data:
  num_words: 794        
  multi_distractor: True
  corpus:
    n_talkers: [1,5]
    with_audioset: True
    root: '/om2/user/msaddler/projects/ibmHearingAid/assets/data/datasets/JSIN_v3.00/nStim_20000/2000ms/rms_0.1/noiseSNR_-10_10/stimSR_20000/reverb_none/noise_all/JSIN_all_v3/subsets/' # Path to raw GigaSpeech dataset
  audio:                                  # Attributes of audio feature
    rep_type:  'cochlea_filt'
    rep_kwargs:
      sr: 20000
      env_sr: 8000
      n_channels: 40
      low_lim: 40
      use_pad: True
      rep_on_gpu: False
      env_extraction_type: 'Half-wave Rectification'
      downsampling_type: 'TorchTransformsResample'
      downsampling_kwargs:
        lowpass_filter_width: 64
        rolloff: 0.9475937167399596
        resampling_method: "kaiser_window"
        beta: 14.769656459379492
    compression_type: 'coch_p3'
    compression_kwargs:
      scale: 1
      offset: 0.0000001   
      clip_value: 5
      power: 0.3
  loader:
    batch_size: 256                         # Gets divided by num gpus
#     num_workers: 20

noise_kwargs: # parameters for background signal levels 
  low_snr: -10
  high_snr: 10

val_metric: 'ACC/val_acc'
model_name: 'FCAttnOnly'
matched_cue_level: True 
layernorm_first: True
fc_attn_only: True
attn_constraints:
  slope: True
hparas:                                   # Experiment hyper-parameters
  valid_step: 5000
  epochs: 10
  optimizer: 'Adam'
  lr: 0.0001
  eps: 0.00000001                         # 1e-8
  lr_scheduler: 'fixed'                   # 'fixed'/'warmup'
  curriculum: 0
  gradient_clip_val: 100 
  

    
  
