
data:
  num_words: 794        
  fc_size: 512

  multi_distractor: True
  corpus:
    n_talkers: [1,5]
    with_audioset: True
    root: '/om2/user/msaddler/projects/ibmHearingAid/assets/data/datasets/JSIN_v3.00/nStim_20000/2000ms/rms_0.1/noiseSNR_-10_10/stimSR_20000/reverb_none/noise_all/JSIN_all_v3/subsets/' # Path to raw GigaSpeech dataset
  audio:                                  # Attributes of audio feature
    rep_type:  'cochlea_filt'
    rep_kwargs:
      sr: 20000
      env_sr: 8000
      n_channels: 40
      low_lim: 40
      use_pad: True
      rep_on_gpu: True
      impulse_len: 0.20
      env_extraction_type: 'Half-wave Rectification'
      downsampling_type: 'TorchTransformsResample'
      downsampling_kwargs:
        lowpass_filter_width: 64
        rolloff: 0.9475937167399596
        resampling_method: "kaiser_window"
        beta: 14.769656459379492
    compression_type: 'coch_p3'
    compression_kwargs:
      scale: 1
      offset: 0.0000001   
      clip_value: 5
      power: 0.3
  loader:
    batch_size: 1024                         # Gets divided by num gpus
#     num_workers: 20

noise_kwargs: # parameters for background signal levels 
  low_snr: -10
  high_snr: 10

val_metric: 'ACC/val_acc'
model_name: 'ModernCNN'
matched_cue_level: False 
layernorm_first: True
per_kernel_attn: False
attn_constraints:
  slope: True
hparas:                                   # Experiment hyper-parameters
  valid_step: 500
  epochs: 10
  optimizer: 'AdamW'
  lr: 0.0001
  eps: 0.00000001                         # 1e-8
  lr_scheduler: 'fixed'                   # 'fixed'/'warmup'
  curriculum: 0
  gradient_clip_val: 100 


model:                                    # Model architecture
  input_c: 1                              # Monaural model
  input_h: 40                             # 40 channels in coch model
  input_w: 16000                          # 2 seconds @ 20kHz
  norm:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1,1,1,1,1,1, 1, 1 ]
  out_channels: [32, 64, 256, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512,512,512,512, 512,512]                       
  kernel:  [[2, 34], [2, 14], [5, 5], [5, 5], [6, 6], [5, 5], [6, 6], [6, 6,], [6, 6], [6, 6], [3, 3],[3, 3],[3, 3],[3, 3],[3, 3],[3, 3], [3, 3], [3, 3]]
  stride: [[1,1], [1,1], [1,1], [1,1], [1,1], [1,1], [1,1], [1,1], [1,1], [1,1], [1,1],[1,1],[1,1],[1,1],[1,1],[1,1], [1,1], [1,1]]
  padding: ['same', 'same', 'same', 'same', 'same', 'same', 'same', 'same', 'same', 'same','same','same','same','same','same','same', 'same', 'same']
  pool: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1,1,1,1,1,1, 1, 1]
  pool_stride: [[2, 4], [2, 4], [1, 5], [1, 4], [1, 1], [1, 1], [2, 4], [1, 1], [1, 1], [1, 1], [2,2], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [2,2], [1,1]]
  pool_size: [[9, 13], [9, 13], [1, 13], [1, 13], [1, 1], [1, 1], [6, 13], [1, 1], [1, 1], [1, 1], [8,8], [1, 1], [1, 1], [1, 1], [1, 1], [1, 1], [8,8], [1, 1]]
  pool_padding: [[4,6], [4,6], [0,6], [0,6], [0,0], [0,0], [3,6], [0,0], [0,0], [0,0], [2,2], [0,0], [0,0], [0,0], [0,0], [0,0], [2,2], [0,0]]
  attn: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1,1,1,1,1,1, 1, 1]
  conv_type: 'SeparableConv2d'
  act_type: 'GELU'
  standard_classifier: False
  global_avg_pool: True
  num_classes:                         # 998 words in cv vocab
    num_words: 794
  fc_size: 512
  global_avg_cue: False
  dropout: 0.6
  attn_constraints:
    slope: True
  
    
  
