# Most of the parameters will be imported from the training config
src:
  ckpt: 'ckpt/lib_word_example_sd0/best_att.pth'
  config: 'config/libri/lib_word_example.yaml'
data:
  corpus:
    name:  'Librispeech'
    path: '/om/data/public/librispeech/librispeech_data/librispeech_data/'
    dev_split: ['dev-clean']
    test_split: ['test-clean']
decode:
  beam_size: 1
  min_len_ratio: 0.01
  max_len_ratio: 0.07
#   lm_path: 'ckpt/lm_example_sd0/best_ppx.pth'
#   lm_config: 'config/libri/lm_example.yaml'
  lm_weight: 0
