corpus:
  name: 'spatialized_commonvoice_gise_scenes'
  cue_type: "mixed"
  task: "word"
  root: '/om/scratch/Mon/imgriff/datasets/spatial_audio_pipeline/assets/dataset_binaural_attn/v04'
  with_cue_free: False
  mixture_percentages:
    voice_only: 0.8
    voice_and_location: 0.1
    location_only: 0.1

audio:                                  # Attributes of audio feature
  rep_type:  'cochlea_filt'
  rep_kwargs:
    sr: 50000
    env_sr: 10000
    n_channels: 40
    low_lim: 40
    use_pad: True
    binaural: True
    rep_on_gpu: True
    center_crop: True
    out_dur: 2  ## in seconds
    impulse_len: 0.25
    env_extraction_type: 'Half-wave Rectification'
    downsampling_type: 'TorchTransformsResample'
    downsampling_kwargs:
      lowpass_filter_width: 64
      rolloff: 0.9475937167399596
      resampling_method: "kaiser_window"
      beta: 14.769656459379492
  compression_type: 'coch_p3'
  compression_kwargs:
    scale: 1
    offset: 0.0000001   
    clip_value: 5
    power: 0.3


val_metric: 'ACC/val_acc'
model_name: 'binaural_attn_cue_voice_and_loc'

noise_kwargs: # parameters for background signal levels 
  low_snr: -10
  high_snr: 10

hparas:                                   # Experiment hyper-parameters
  valid_step: 1000
  epochs: 1000
  optimizer: 'AdamW'
  lr: 0.0001
  eps: 0.00000001                         # 1e-8
  gradient_clip_val: 100 
  batch_size: 768                        # Gets divided by num gpus

model:                                    # Model architecture
  input_sr: 10000
  out_channels: [32, 64, 256, 512, 512, 512, 512]                       
  kernel:  [[2, 34], [2, 14], [5, 5], [5, 5], [6, 6], [5, 5], [6, 6]]
  stride: [[1,1], [1,1], [1,1], [1,1], [1,1], [1,1], [1,1]]
  padding: ['same', 'same', 'same', 'same', 'same', 'same', 'same']
  pool_stride: [[2, 4], [2, 4], [1, 5], [1, 4], [1, 1], [1, 1], [2, 4]] 
  pool_size: [[9, 13], [9, 13], [1, 13], [1, 13], [1, 1], [1, 1], [6, 13]]
  pool_padding: [[4,6], [4,6], [0,6], [0,6], [0,0], [0,0], [3,6]]
  attn: [1, 1, 1, 1, 1, 1, 1]
  num_classes:                         # 998 words in cv vocab
    num_words: 800
  fc_size: 512
  global_avg_cue: False
  dropout: 0.6
  attn_constraints:
    slope: True
